export enum ActionType {
  READY = 'READY',
  ASK = 'ASK',
  WAIT = 'WAIT',
  HOLE_CARDS = 'HOLE_CARDS',
  BET = 'BET',
  CALL = 'CALL',
  CHECK = 'CHECK',
  FOLD = 'FOLD',
  RAISE = 'RAISE',
  SMALL_BLIND = 'SMALL_BLIND',
  BIG_BLIND = 'BIG_BLIND',
  ANTE = 'ANTE',
  ALL_IN = 'ALL_IN',
  WIN = 'WIN',
  LOSE = 'LOSE',
  USE_TIME_BANK = 'USE_TIME_BANK',
}
